name: Run tests

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Run all tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Set up Go
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.18.0'
        check-latest: true

    - run: cd cmd/kvapi && go build main.go
    - run: cd cmd/sim && go run main.go util.go